### ISSUE TITLE
The 'Invoke-DQVTesting' command was found in the module 'Invoke-DQVTesting', but the module could not be loaded.

### ISSUE THREAD

**Issue by mdieperink** [kerski/fabric-dataops-patterns#12]
The Invoke-DQVTesting module does't load anymore and fails silently. This happens when running a pipeline with the `DAX Query View Testing Pattern/scripts/Run-CICD.yml` code.

I think it has something to do with the version bump of the Microsoft.AnalysisServices.NetCore assembly in the Microsoft repo
[here](https://github.com/microsoft/Analysis-Services/commit/732e77348c93c81680662c2f93c1d3022b7fe4bb), but I have limited knowledge of assembly dependency shenanigans.

Error message:
```
Invoke-DQVTesting : The 'Invoke-DQVTesting' command was found in the module 'Invoke-DQVTesting', but the module could not be loaded. For more information, run 'Import-Module Invoke-DQVTesting'.
At D:\a\_temp\fcb4c22d-9603-4314-a1a2-921092cda497.ps1:227 char:9
+         Invoke-DQVTesting -WorkspaceName "${env:WORKSPACE_NAME}" `
+         ~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Invoke-DQVTesting:String) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
```

**Comment by kerski** [comment]
Running Pester tests to verify a fix is in place.

**Comment by kerski** [comment]
Could you try the release candidate?: https://www.powershellgallery.com/packages/Invoke-DQVTesting/0.0.13-rc

**Comment by mdieperink** [comment]
I will be able to try on Monday. I will get back to you then. 

Thanks for looking into this!

**Comment by mdieperink** [comment]
I can confirm it's working with 0.0.13-rc

**Comment by mdieperink** [comment]
i spoke too soon, I still get the `The 'Invoke-DQVTesting' command was found in the module 'Invoke-DQVTesting', but the module could not be loaded.` error. I don't know what you changed, but I got it working on my side. I'll create a PR.
